[2021-10-05 00:22:50,545][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 00:22:50,594][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:21:28,124][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:21:28,167][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:21:32,284][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:21:32,327][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 11:25:14,719][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 11:25:17,534][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:25:17,574][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 11:25:17,694][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:25:17,733][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:28:44,674][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 11:28:47,488][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:28:47,522][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 11:28:47,618][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:28:47,666][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:29:56,162][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 11:29:58,980][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:29:59,025][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 11:29:59,115][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:29:59,159][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:30:39,872][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 11:30:42,651][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:30:42,696][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 11:30:42,796][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:30:42,839][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:40:04,484][logger.py 61][INFO]: ------开始执行hbq------
[2021-10-05 11:40:04,484][logger.py 65][ERROR]: ------hbq执行失败，失败原因：------
[2021-10-05 11:40:04,484][logger.py 66][ERROR]: hbq is error,here are details:Traceback (most recent call last):
  File "D:/daima/xin-daima/two-pytest-api-automation/common/logger.py", line 63, in log
    func(*args, **kwargs)
  File "D:/daima/xin-daima/two-pytest-api-automation/common/logger.py", line 75, in hbq
    assert 1==2
AssertionError

[2021-10-05 11:49:22,554][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 11:49:25,322][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:49:25,355][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 11:49:25,458][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:49:25,502][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:52:33,071][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 11:52:35,887][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:52:35,931][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 11:52:36,034][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:52:36,075][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:56:24,760][logger.py 61][INFO]: ------开始执行test_admin_login------
[2021-10-05 11:56:24,811][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 11:56:29,346][logger.py 61][INFO]: ------开始执行test_get_auth_code------
[2021-10-05 11:56:29,474][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 16:33:47,144][logger.py 61][INFO]: ------开始执行hbq------
[2021-10-05 16:33:47,145][logger.py 65][ERROR]: ------hbq执行失败，失败原因：------
[2021-10-05 16:33:47,145][logger.py 66][ERROR]: hbq is error,here are details:Traceback (most recent call last):
  File "D:/daima/xin-daima/two-pytest-api-automation/common/logger.py", line 63, in log
    func(*args, **kwargs)
  File "D:/daima/xin-daima/two-pytest-api-automation/common/logger.py", line 75, in hbq
    assert 1==2
AssertionError

[2021-10-05 16:34:50,902][logger.py 61][INFO]: ------开始执行hbq用例------
[2021-10-05 16:34:50,902][logger.py 65][ERROR]: ------hbq用例执行失败，失败原因：------
[2021-10-05 16:34:50,903][logger.py 66][ERROR]: hbq 用例 is error,here are details:Traceback (most recent call last):
  File "D:/daima/xin-daima/two-pytest-api-automation/common/logger.py", line 63, in log
    func(*args, **kwargs)
  File "D:/daima/xin-daima/two-pytest-api-automation/common/logger.py", line 75, in hbq
    assert 1==2
AssertionError

[2021-10-05 16:38:40,100][logger.py 61][INFO]: ------开始执行test_admin_login用例------
[2021-10-05 16:38:40,145][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 16:41:48,116][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 16:41:48,843][logger.py 61][INFO]: ------开始执行test_get_auth_code用例------
[2021-10-05 16:41:48,877][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 16:41:48,982][logger.py 61][INFO]: ------开始执行test_admin_login用例------
[2021-10-05 16:41:49,029][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 16:46:26,524][main.py 16][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-10-05 16:46:27,309][logger.py 61][INFO]: ------开始执行test_get_auth_code用例------
[2021-10-05 16:46:27,360][logger.py 69][INFO]: ------test_get_auth_code执行成功------
[2021-10-05 16:46:27,474][logger.py 61][INFO]: ------开始执行test_admin_login用例------
[2021-10-05 16:46:27,520][logger.py 69][INFO]: ------test_admin_login执行成功------
[2021-10-05 16:46:59,361][logger.py 61][INFO]: ------开始执行test_admin_login用例------
[2021-10-05 16:46:59,413][logger.py 69][INFO]: ------test_admin_login执行成功------
