{"uuid": "c05976c6-aa17-49bb-bc71-9d444d006966", "children": ["9cce8333-1fbf-470f-a188-aae166e371bd", "453b1316-d82a-4f7e-bab9-54b0cb44d8ca", "d040c361-6096-4d8b-8f18-f4dfdeb37232"], "befores": [{"name": "ls_login", "status": "failed", "statusDetails": {"message": "AssertionError: 前台登录失败\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation\\case\\conftest.py\", line 48, in ls_login\n    login_ls(lisi_info,'lisi_token')\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation\\common\\logintoken.py\", line 63, in login_ls\n    return Login(admin_info,ls_token)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation\\common\\logintoken.py\", line 27, in __init__\n    assert result['code'] == 200,\"前台登录失败\"\n"}, "steps": [{"name": "admin账号登录", "status": "passed", "steps": [{"name": "响应日志", "status": "passed", "parameters": [{"name": "status_code", "value": "200"}, {"name": "text", "value": "{'code': 500, 'message': 'Bad credentials', 'data': None}"}], "start": 1636622848477, "stop": 1636622848477}, {"name": "请求日志", "status": "passed", "parameters": [{"name": "url", "value": "'http://121.37.169.128:8201/mall-member/sso/login?platform=test&time=1636622848426&password=123456&username=admin1'"}, {"name": "method", "value": "'post'"}, {"name": "body", "value": "{}"}, {"name": "headers", "value": "{'Content-Type': 'application/json'}"}], "start": 1636622848477, "stop": 1636622848477}], "start": 1636622848426, "stop": 1636622848477}], "start": 1636622848426, "stop": 1636622848477}], "start": 1636622848426, "stop": 1636622848561}