{"uuid": "8d272536-31cd-4e07-959c-484e70c6d4a9", "children": ["b3686649-c74b-4b4c-a993-baae2e749d81", "b5a95585-6e15-4ad8-90fe-182150675669", "5c6157d0-1eae-4ea2-9fd9-f0044558eb65"], "befores": [{"name": "als_login", "status": "broken", "statusDetails": {"message": "TypeError: login() missing 1 required positional argument: 'self'\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\conftest.py\", line 30, in als_login\n    login_ls(lisi_info,'lisi_token')\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 87, in login_ls\n    return Login(admin_info,ls_token)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 63, in __init__\n    result = login(username=self.username, password=self.password)\n"}, "start": 1648177135582, "stop": 1648177135582}], "start": 1648177135582, "stop": 1648177135667}