{"name": "test_get_auth_code[case1_获取验证码成功1]", "status": "broken", "statusDetails": {"message": "KeyError: 'telephone'", "trace": "self = <case.test_member_controller.test_auth_code.TestGetAuthCode object at 0x00000160E0A20668>\ncase_data = {'body': {'telephone1': '18821768019'}, 'case_name': 'case1_获取验证码成功', 'expect': {'code': 400, 'message': ''}}\nmember_controller_z = <api.admin.member_controller_api.MemberControllerApi object at 0x00000160E0A68240>\n\n    @allure.step('随机手机号-获取验证码')#测试报告显示步骤\n    @pytest.mark.parametrize(\"case_data\", data,\n                             ids=[data[i]['case_name'] for i in range(len(data))])  # 参数化测试用例\n    @decorate_log\n    def test_get_auth_code(self,case_data, member_controller_z):\n        # time.sleep(3)\n        case_body = case_data['body']\n>       actual_data = member_controller_z.get_auth_code(telephone = case_body['telephone'])\nE       KeyError: 'telephone'\n\ntest_auth_code.py:26: KeyError"}, "steps": [{"name": "随机手机号-获取验证码", "status": "broken", "statusDetails": {"message": "KeyError: 'telephone'\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logger.py\", line 68, in log\n    raise e\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logger.py\", line 64, in log\n    func(*args, **kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\case\\test_member_controller\\test_auth_code.py\", line 26, in test_get_auth_code\n    actual_data = member_controller_z.get_auth_code(telephone = case_body['telephone'])\n"}, "parameters": [{"name": "args", "value": "(<case.test_member_controller.test_auth_code.TestGetAuthCode object at 0x00000160E0A20668>,)"}, {"name": "case_data", "value": "{'case_name': 'case1_获取验证码成功', 'body': {'telephone1': '18821768019'}, 'expect': {'message': '', 'code': 400}}"}, {"name": "member_controller_z", "value": "<api.admin.member_controller_api.MemberControllerApi object at 0x00000160E0A68240>"}], "start": 1648110232131, "stop": 1648110232132}], "attachments": [{"name": "log", "source": "bb74501d-d2cf-4d00-9a17-dace202a6692-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case_data", "value": "{'case_name': 'case1_获取验证码成功', 'body': {'telephone1': '18821768019'}, 'expect': {'message': '', 'code': 400}}"}], "start": 1648110232131, "stop": 1648110232143, "uuid": "6df90c47-68fe-4285-a05d-4b5bed46231f", "historyId": "c1c7a6b49af34bdc3b21b0ac80c340c7", "testCaseId": "3a3eb53b2248f8dcd92932637269a06c", "fullName": "case.test_member_controller.test_auth_code.TestGetAuthCode#test_get_auth_code", "labels": [{"name": "story", "value": "获取验证码功能"}, {"name": "feature", "value": "测试member_controller模块"}, {"name": "parentSuite", "value": "case.test_member_controller"}, {"name": "suite", "value": "test_auth_code"}, {"name": "subSuite", "value": "TestGetAuthCode"}, {"name": "host", "value": "LAPTOP-9964GMTD"}, {"name": "thread", "value": "53028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_member_controller.test_auth_code"}]}