{"uuid": "4421f18c-5025-4de3-ac6e-91908e91aa3e", "children": ["30242025-7c1c-4e87-b548-9889dfb0b1df", "0035e4f2-7445-4287-829e-98dfbb803ff3", "2fbace75-5217-44a4-b2a7-9741c787f769"], "befores": [{"name": "als_login", "status": "broken", "statusDetails": {"message": "TypeError: login1() missing 1 required positional argument: 'self'\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\conftest.py\", line 30, in als_login\n    login_ls(lisi_info,'lisi_token')\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 85, in login_ls\n    return Login(admin_info,ls_token)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 61, in __init__\n    result = login1(username=self.username, password=self.password)\n"}, "start": 1648177231459, "stop": 1648177231459}], "start": 1648177231459, "stop": 1648177231547}