{"name": "test_admin_login[case3_用户名密码错误的登录]", "status": "broken", "statusDetails": {"message": "NameError: name 'login1' is not defined", "trace": "self = <case.test_member_controller.test_login.Test_DengLu object at 0x0000018F7A8A9B00>\ncase_data = {'body': {'password': '9999997', 'username': 'adminhhhhhhhhhh'}, 'case_name': 'case3_用户名密码错误的登录', 'expect': {'code': 500, 'message': 'Bad credentials'}}\nmember_controller_z = <api.admin.member_controller_api.MemberControllerApi object at 0x0000018F7A7F32B0>\n\n    @decorate_log\n    @pytest.mark.parametrize(\"case_data\", data,ids=[data[i]['case_name'] for i in range(len(data))])  # 参数化测试用例\n    def test_admin_login(self,case_data,member_controller_z):\n        # time.sleep(10)\n        print(\"case_data\",case_data)\n        case_body = case_data['body']\n        \"\"\"请求登录测试用例\"\"\"\n        with allure.step('登录步骤'):\n            actual_data = member_controller_z.login(password=case_body['password']\n>                          ,username=case_body['username'])\n\ntest_login.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api.admin.member_controller_api.MemberControllerApi object at 0x0000018F7A7F32B0>\nusername = 'adminhhhhhhhhhh', password = '9999997'\n\n    def login(self,username=\"\"\n          , password=\"\"):\n>       return login1()\nE       NameError: name 'login1' is not defined\n\n..\\..\\api\\admin\\member_controller_api.py:67: NameError"}, "steps": [{"name": "登录步骤", "status": "broken", "statusDetails": {"message": "NameError: name 'login1' is not defined\n", "trace": "  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\case\\test_member_controller\\test_login.py\", line 34, in test_admin_login\n    ,username=case_body['username'])\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\api\\admin\\member_controller_api.py\", line 67, in login\n    return login1()\n"}, "start": 1648178049639, "stop": 1648178049639}], "attachments": [{"name": "log", "source": "c87abdc8-33de-4860-8d96-46e6db859d39-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case_data", "value": "{'case_name': 'case3_用户名密码错误的登录', 'body': {'username': 'adminhhhhhhhhhh', 'password': '9999997'}, 'expect': {'message': 'Bad credentials', 'code': 500}}"}], "start": 1648178049639, "stop": 1648178049640, "uuid": "483b296c-d7a4-4a9a-9527-0f3b794ae56e", "historyId": "e8e60fbd9f64690605ffb6f55812c06c", "testCaseId": "02c7f242c9f09fbdefa4b8f5b820915e", "fullName": "case.test_member_controller.test_login.Test_DengLu#test_admin_login", "labels": [{"name": "story", "value": "登录功能"}, {"name": "feature", "value": "测试member_controller模块"}, {"name": "parentSuite", "value": "case.test_member_controller"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_DengLu"}, {"name": "host", "value": "LAPTOP-9964GMTD"}, {"name": "thread", "value": "49660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_member_controller.test_login"}]}