{"uuid": "a96d49f5-94e5-4b08-b7b7-362df3e0faa9", "children": ["fa10d819-ec8f-40b4-815b-9efcd8ecd9c1", "9190c0d4-03c4-4d0d-a3a7-5af61d9d0945", "5c9fbcad-2ec6-47b5-85e1-260b59e61103"], "befores": [{"name": "als_login", "status": "broken", "statusDetails": {"message": "NameError: name 'clent1' is not defined\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\conftest.py\", line 30, in als_login\n    login_ls(lisi_info,'lisi_token')\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 83, in login_ls\n    return Login(admin_info,ls_token)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 43, in __init__\n    login = MemberControllerApi(token).login()\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\api\\admin\\member_controller_api.py\", line 78, in login\n    url = clent1.get_full_url(url, etc=etc)\n"}, "start": 1648177045384, "stop": 1648177045385}], "start": 1648177045384, "stop": 1648177045485}